//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProductPrediction
{
    using System;
    using System.Collections.Generic;
    
    public partial class csta_product_group_level_definition_table
    {
        public string product_group_level_id { get; set; }
        public string table_name { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string active { get; set; }
    
        public virtual csta_product_group_level_definition csta_product_group_level_definition { get; set; }
    }
}
