//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProductPrediction
{
    using System;
    using System.Collections.Generic;
    
    public partial class cstd_company_sales_history
    {
        public string company_sales_history_id { get; set; }
        public string company_id { get; set; }
        public string product_code { get; set; }
        public Nullable<decimal> sales_revenue { get; set; }
        public Nullable<System.DateTime> sales_date { get; set; }
        public string ship_to_num { get; set; }
    
        public virtual oncd_company oncd_company { get; set; }
        public virtual onca_product onca_product { get; set; }
    }
}
