//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProductPrediction
{
    using System;
    using System.Collections.Generic;
    
    public partial class onca_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public onca_product()
        {
            this.cstd_company_sales_history = new HashSet<cstd_company_sales_history>();
        }
    
        public string product_code { get; set; }
        public string manufacturer_code { get; set; }
        public string description { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string active { get; set; }
        public string cst_feature { get; set; }
        public string cst_benefit { get; set; }
        public string cst_part_number { get; set; }
        public string cst_part_number_location { get; set; }
        public string cst_category { get; set; }
        public string cst_tools_and_resources_description { get; set; }
        public Nullable<System.DateTime> cst_expiration_date { get; set; }
        public string cst_class { get; set; }
        public string cst_ist_use { get; set; }
        public string cst_rev { get; set; }
        public string cst_uom { get; set; }
        public string cst_product_group_code { get; set; }
        public string cst_min_lead_time_uom_code { get; set; }
        public string cst_product_group_level_1_code { get; set; }
        public string cst_product_group_level_2_code { get; set; }
        public string cst_product_group_level_3_code { get; set; }
        public string cst_product_group_level_4_code { get; set; }
        public string cst_product_group_level_5_code { get; set; }
        public string cst_product_group_level_6_code { get; set; }
        public string cst_product_group_level_7_code { get; set; }
        public string cst_product_group_level_8_code { get; set; }
        public string cst_order_type_code { get; set; }
        public string cst_created_by_user_code { get; set; }
        public string cst_updated_by_user_code { get; set; }
        public string cst_product_availability_code { get; set; }
        public string cst_sku { get; set; }
        public string cst_alternate_description { get; set; }
        public string cst_upc { get; set; }
        public string cst_dea_certificate_required { get; set; }
        public string cst_product_category_code { get; set; }
        public string cst_product_division_code { get; set; }
        public string cst_product_brand_code { get; set; }
        public string cst_inventory_status_code { get; set; }
        public Nullable<decimal> cst_min_lead_time { get; set; }
        public Nullable<System.DateTime> cst_new_distribution_until_date { get; set; }
        public Nullable<System.DateTime> cst_first_ship_date { get; set; }
        public Nullable<System.DateTime> cst_last_ship_date { get; set; }
        public Nullable<System.DateTime> cst_first_order_date { get; set; }
        public Nullable<System.DateTime> cst_last_order_date { get; set; }
        public string cst_track_availability { get; set; }
        public string cst_sku_type_code { get; set; }
        public Nullable<System.DateTime> cst_creation_date { get; set; }
        public Nullable<System.DateTime> cst_updated_date { get; set; }
        public string cst_create_opportunity { get; set; }
        public string cst_opportunity_seed { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> quantity_on_hand { get; set; }
        public Nullable<decimal> ytd_quantity_sold { get; set; }
        public Nullable<decimal> ytd_amount_sold { get; set; }
        public string cst_idh_number { get; set; }
        public string cst_mfgno { get; set; }
        public Nullable<decimal> cst_pack { get; set; }
        public Nullable<decimal> cst_wt { get; set; }
        public Nullable<int> cst_sfx { get; set; }
        public string cst_item_upc { get; set; }
        public string cst_upc_prefix { get; set; }
        public string cst_upc_suffix { get; set; }
        public string cst_ordering_unit { get; set; }
        public string cst_mcs_brand_code { get; set; }
        public string cst_vendor_item_code { get; set; }
        public string cst_gtin_code { get; set; }
        public string cst_misc1_code { get; set; }
        public string cst_misc2_code { get; set; }
        public string cst_discontinued_flag { get; set; }
        public Nullable<System.DateTime> cst_discontinued_date { get; set; }
        public Nullable<decimal> cst_product_length { get; set; }
        public Nullable<decimal> cst_product_width { get; set; }
        public Nullable<decimal> cst_product_height { get; set; }
        public Nullable<decimal> cst_case_length { get; set; }
        public Nullable<decimal> cst_case_width { get; set; }
        public Nullable<decimal> cst_case_height { get; set; }
        public Nullable<decimal> cst_pallet_length { get; set; }
        public Nullable<decimal> cst_pallet_width { get; set; }
        public Nullable<decimal> cst_pallet_height { get; set; }
        public Nullable<decimal> cst_case_per_layer { get; set; }
        public Nullable<decimal> cst_layer_per_pallet { get; set; }
        public Nullable<decimal> cst_case_per_pallet { get; set; }
        public Nullable<decimal> cst_minimum_amount { get; set; }
        public string cst_minimum_unit { get; set; }
        public Nullable<decimal> cst_shelf_life { get; set; }
        public string cst_shelf_life_units { get; set; }
        public Nullable<decimal> cst_size { get; set; }
        public string cst_size_units { get; set; }
        public Nullable<decimal> cst_case_each { get; set; }
        public Nullable<decimal> cst_pack_each { get; set; }
        public Nullable<decimal> cst_each { get; set; }
        public string mcs_product_flag { get; set; }
        public Nullable<System.DateTime> cst_effective_date { get; set; }
    
        public virtual csta_product_group csta_product_group { get; set; }
        public virtual csta_product_group_level_1_values csta_product_group_level_1_values { get; set; }
        public virtual csta_product_group_level_2_values csta_product_group_level_2_values { get; set; }
        public virtual csta_product_group_level_3_values csta_product_group_level_3_values { get; set; }
        public virtual csta_product_group_level_4_values csta_product_group_level_4_values { get; set; }
        public virtual csta_product_group_level_5_values csta_product_group_level_5_values { get; set; }
        public virtual csta_product_group_level_6_values csta_product_group_level_6_values { get; set; }
        public virtual csta_product_group_level_7_values csta_product_group_level_7_values { get; set; }
        public virtual csta_product_group_level_8_values csta_product_group_level_8_values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cstd_company_sales_history> cstd_company_sales_history { get; set; }
    }
}
