//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProductPrediction
{
    using System;
    using System.Collections.Generic;
    
    public partial class onca_phone_type
    {
        public string phone_type_code { get; set; }
        public string description { get; set; }
        public string active { get; set; }
        public string device_type { get; set; }
    }
}
