//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProductPrediction
{
    using System;
    using System.Collections.Generic;
    
    public partial class oncd_company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oncd_company()
        {
            this.cstd_company_sales_history = new HashSet<cstd_company_sales_history>();
            this.oncd_company1 = new HashSet<oncd_company>();
        }
    
        public string company_id { get; set; }
        public string company_name_1 { get; set; }
        public string company_name_2 { get; set; }
        public string company_name_1_search { get; set; }
        public string company_name_2_search { get; set; }
        public string company_name_1_soundex { get; set; }
        public string company_name_2_soundex { get; set; }
        public Nullable<int> annual_sales { get; set; }
        public Nullable<int> number_of_employees { get; set; }
        public string profile_code { get; set; }
        public string external_id { get; set; }
        public string company_type_code { get; set; }
        public string contact_method_code { get; set; }
        public string do_not_solicit { get; set; }
        public string company_status_code { get; set; }
        public string duplicate_check { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string created_by_user_code { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by_user_code { get; set; }
        public Nullable<System.DateTime> status_updated_date { get; set; }
        public string status_updated_by_user_code { get; set; }
        public string parent_company_id { get; set; }
        public string ticker_symbol { get; set; }
        public string cst_do_not_call_flag { get; set; }
        public Nullable<System.DateTime> cst_do_not_call_date { get; set; }
        public string cst_on_hold_flag { get; set; }
        public string cst_on_hold_reason_code { get; set; }
        public string cst_is_spanish_flag { get; set; }
        public Nullable<int> cst_attempts { get; set; }
        public string cst_company_rank_code { get; set; }
        public Nullable<System.DateTime> cst_rest_until_date { get; set; }
        public Nullable<int> cst_yearly_call_frequency { get; set; }
        public Nullable<int> cst_attempts_year_to_date { get; set; }
        public string cst_company_association_type_code { get; set; }
        public string cst_cma_no { get; set; }
        public string cst_facility_type_code { get; set; }
        public string cst_do_not_fax_flag { get; set; }
        public string cst_do_not_email_flag { get; set; }
        public string cst_do_not_mail_flag { get; set; }
        public string cst_dns_flag { get; set; }
        public string cst_dnscc_flag { get; set; }
        public string cst_prescriber { get; set; }
        public string cst_prescriber_title { get; set; }
        public string cst_ims_number { get; set; }
        public string cst_account_number { get; set; }
        public string cst_field_rep_code { get; set; }
        public string cst_region_code { get; set; }
        public string cst_regional_manager_code { get; set; }
        public string cst_completed_flag { get; set; }
        public Nullable<System.Guid> cst_program_flow_id { get; set; }
        public string cst_tdlinx_account_code { get; set; }
        public string cst_tdlinx_store_code { get; set; }
        public string cst_client_cot_code { get; set; }
        public string cst_west_cot_code { get; set; }
        public string cst_client_segment_code { get; set; }
        public string cst_west_segment_code { get; set; }
        public string cst_contact_frequency_code { get; set; }
        public string cst_client_account_number { get; set; }
        public string cst_client_company_id { get; set; }
        public Nullable<System.DateTime> cst_creation_admin_date { get; set; }
        public string cst_require_samples { get; set; }
        public string cst_client_focus_account { get; set; }
        public string cst_west_focus_code { get; set; }
        public string cst_use_custom_product_codes { get; set; }
        public string cst_special_shipping_instructions { get; set; }
        public Nullable<decimal> cst_spend_rate { get; set; }
        public Nullable<decimal> cst_projected_spend_rate { get; set; }
        public string cst_allow_closeouts { get; set; }
        public string cst_allow_non_promotable_sku { get; set; }
        public string cst_company_stage_code { get; set; }
        public Nullable<decimal> cst_accrued_amount { get; set; }
        public Nullable<decimal> cst_projected_funding_amount { get; set; }
        public string cst_price_bracket_code { get; set; }
        public string sold_to { get; set; }
        public string cst_coverage_code { get; set; }
        public string cst_hierarchy_id { get; set; }
        public string cst_hierarchy_name { get; set; }
        public Nullable<decimal> cst_annual_sales { get; set; }
        public Nullable<System.DateTime> cst_on_hold_date { get; set; }
        public Nullable<System.DateTime> cst_completion_date { get; set; }
        public Nullable<System.DateTime> cst_on_hold_start_date { get; set; }
        public Nullable<System.DateTime> cst_on_hold_end_date { get; set; }
        public Nullable<int> cst_store_count { get; set; }
        public string cst_mcs_code { get; set; }
        public Nullable<long> Owner_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cstd_company_sales_history> cstd_company_sales_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oncd_company> oncd_company1 { get; set; }
        public virtual oncd_company oncd_company2 { get; set; }
    }
}
