//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProductPrediction
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onc_pg_famEntities : DbContext
    {
        public onc_pg_famEntities()
            : base("name=onc_pg_famEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<csta_product_group> csta_product_group { get; set; }
        public virtual DbSet<csta_product_group_level_1_values> csta_product_group_level_1_values { get; set; }
        public virtual DbSet<csta_product_group_level_2_values> csta_product_group_level_2_values { get; set; }
        public virtual DbSet<csta_product_group_level_3_values> csta_product_group_level_3_values { get; set; }
        public virtual DbSet<csta_product_group_level_4_values> csta_product_group_level_4_values { get; set; }
        public virtual DbSet<csta_product_group_level_5_values> csta_product_group_level_5_values { get; set; }
        public virtual DbSet<csta_product_group_level_6_values> csta_product_group_level_6_values { get; set; }
        public virtual DbSet<csta_product_group_level_7_values> csta_product_group_level_7_values { get; set; }
        public virtual DbSet<csta_product_group_level_8_values> csta_product_group_level_8_values { get; set; }
        public virtual DbSet<csta_product_group_level_definition> csta_product_group_level_definition { get; set; }
        public virtual DbSet<csta_product_group_level_definition_table> csta_product_group_level_definition_table { get; set; }
        public virtual DbSet<cstd_company_sales_history> cstd_company_sales_history { get; set; }
        public virtual DbSet<onca_phone_type> onca_phone_type { get; set; }
        public virtual DbSet<onca_product> onca_product { get; set; }
        public virtual DbSet<oncd_company> oncd_company { get; set; }
    }
}
